### ISSUE TITLE
StackOverflowError in Stacked.chain for large json

### ISSUE THREAD

**Issue by SheliakLyr** [gnieh/diffson#63]
Tested using version 2.1.0 with scala 2.11.

`java.lang.StackOverflowError: null
at gnieh.diffson.Stacked.chain$lzycompute(Patience.scala:200)
at gnieh.diffson.Stacked.chain(Patience.scala:200)
at gnieh.diffson.Stacked.chain$lzycompute(Patience.scala:202)
at gnieh.diffson.Stacked.chain(Patience.scala:200)
at gnieh.diffson.Stacked.chain$lzycompute(Patience.scala:202)
at gnieh.diffson.Stacked.chain(Patience.scala:200)
at gnieh.diffson.Stacked.chain$lzycompute(Patience.scala:202)
at gnieh.diffson.Stacked.chain(Patience.scala:200)`

**Comment by satabin** [comment]
Hi,

Is that ok if I fix it from 2.2.2 on or do you want to stick with series 2.1.x?

**Comment by SheliakLyr** [comment]
Thank you. I can upgrade to 2.2.x without problems as long it cross-compiles to scala 2.11.

**Comment by satabin** [comment]
Just a warning: diffson 2.2.x depends on Play! Json 2.6.0 which has breaking changes with 2.5.0 (used by diffson 2.1.x). So if you are using the Play! Json backend you may have troubles.

**Comment by satabin** [comment]
I just released version 2.2.2 with the fix.
