### ISSUE TITLE
NoSuchMethodError with circe 0.9.0-M2

### ISSUE THREAD

**Issue by woky** [gnieh/diffson#66]
Hi. I'm trying diffson (and circe) for the first time. I usually use `latest.integration` for libraries I play with. With scala 2.12.4, circe 0.9.0-M2 and diffson 2.2.3, I've tried the following code

```
import io.circe._
import io.circe.parser._
import gnieh.diffson.circe._

val jsonText1 = """
{
  "a": 1,
  "b": "foo"
}
"""

val jsonText2 = """
{
  "a": 1,
  "b": "bar"
}
"""

val result = for {
  json1 <- parse(jsonText1)
  json2 <- parse(jsonText2)
} yield {
  JsonDiff.diff(json1, json2, true)
}
println(result)
```

and got the following error

```
java.lang.NoSuchMethodError: io.circe.Encoder$.encodeList(Lio/circe/Encoder;)Lio/circe/Encoder;
	at gnieh.diffson.CirceInstance$DiffsonProtocol.jsonPatchEncoder(CirceInstance.scala:118)
	at gnieh.diffson.CirceInstance$DiffsonProtocol.jsonPatchEncoder$(CirceInstance.scala:117)
	at gnieh.diffson.CirceInstance$DiffsonProtocol$.jsonPatchEncoder(CirceInstance.scala:29)
	at gnieh.diffson.CirceInstance$provider$.<init>(CirceInstance.scala:161)
	at gnieh.diffson.CirceInstance.provider$lzycompute$1(CirceInstance.scala:132)
	at gnieh.diffson.CirceInstance.provider(CirceInstance.scala:132)
	at gnieh.diffson.CirceInstance.provider(CirceInstance.scala:27)
	at gnieh.diffson.JsonDiffSupport$JsonDiff.diff(JsonDiff.scala:75)
	at gnieh.diffson.JsonDiffSupport$JsonDiff.diff(JsonDiff.scala:53)
	at Playground.$anonfun$result$2(main.scala:25)
	at scala.util.Either.map(Either.scala:350)
	at Playground.$anonfun$result$1(main.scala:23)
	at scala.util.Either.flatMap(Either.scala:338)
	at Playground.<init>(main.scala:22)
	at Main$.<init>(main.scala:31)
	at Main$.<clinit>(main.scala)
	at Main.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:748)
```
Here's the _scaste_: https://scastie.scala-lang.org/4toyiCC1S4GFiRBrDadlMg

I'm not sure where should I report the issue. It seems to me it's Scala compiler error.

**Comment by satabin** [comment]
Hi,

Diffson is compiled against circe 0.8.0. If the API changed in 0.9.0 then it is "normal" that this kind of error occurs. Moreover, this circe version is still a milestone version. Once it becomes a new stable version I will review the changes to see if I can update the circe dependency at low cost in diffson. I am always reluctant to update to a new major version inside a minor version of diffson.

**Comment by satabin** [comment]
More specifically, the signature of [`Encoder.encodeList`](https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Encoder.scala#L260) changed in this new circe version. That’s what is causing this error.

**Comment by fsvehla** [comment]
Circe 0.9 is now released

**Comment by satabin** [comment]
See PR #68

**Comment by stephennancekivell** [comment]
Hey, I can confirm I had the same problem with diffson#2.2.4 and circe#0.9.0 upgrading to diffson#2.2.5 fixed it.
